'use client';
import {useState} from 'react';
import {ExtraBlock,readExtras} from '@/lib/extras';
import {exportInventory,captionText} from '@/lib/export-model';
import {ProposalData} from '@/lib/proposal';
export function ExtrasPreview({data,field}:{data:ProposalData,field:string}){return <>{(readExtras(data)[field]||[]).map(b=><figure className="proposal-extra" key={b.id}>{b.type==='picture'?<img src={'/api/media/'+b.assetId} alt={b.caption||'Proposal picture'}/>:<div className="extra-table-scroll"><table><tbody>{b.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=>i===0?<th key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}<figcaption>{captionText(exportInventory(data).find(e=>e.id===b.id)!)}</figcaption></figure>)}</>;}
export function ExtrasEditor({data,field,onChange}:{data:ProposalData,field:string,onChange:(value:string)=>void}){const [uploading,setUploading]=useState(false),[error,setError]=useState('');const extras=readExtras(data),blocks=extras[field]||[];
 function change(next:ExtraBlock[]){onChange(JSON.stringify({...extras,[field]:next}));}
 function patch(id:string,values:Partial<ExtraBlock>){change(blocks.map(b=>b.id===id?{...b,...values} as ExtraBlock:b));}
 return <div className="extras-editor"><div className="actions"><button type="button" className="secondary" disabled={blocks.length>=6} onClick={()=>change([...blocks,{id:crypto.randomUUID(),type:'table',caption:'',rows:[['','',''],['','',''],['','','']]}])}>Add table</button><label className="secondary picture-upload">{uploading?'Uploading…':'Add picture'}<input type="file" accept="image/png,image/jpeg" disabled={uploading||blocks.length>=6} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setError('');try{const form=new FormData();form.append('picture',file);const res=await fetch('/api/media',{method:'POST',body:form});const result=await res.json() as {id:string,error?:string};if(!res.ok)throw new Error(result.error);change([...blocks,{id:crypto.randomUUID(),type:'picture',caption:'',assetId:result.id}]);}catch(err){setError((err as Error).message);}finally{setUploading(false);e.target.value='';}}}/></label></div><p className="fine">Tables and pictures are saved with this item and included in the PDF and Word exports. PNG or JPG, up to 5 MB.</p>{error&&<p role="alert" className="error">{error}</p>}{blocks.map(b=><div className="extra-edit" key={b.id}>{b.type==='picture'?<img src={'/api/media/'+b.assetId} alt={b.caption||'Uploaded picture'}/>:<><div className="extra-table-scroll"><table><tbody>{b.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}><textarea aria-label={`Table row ${i+1}, column ${j+1}`} rows={2} value={cell} onChange={e=>patch(b.id,{rows:b.rows.map((r,n)=>n===i?r.map((c,m)=>m===j?e.target.value:c):r)})}/></td>)}</tr>)}</tbody></table></div><div className="actions"><button className="secondary" disabled={b.rows.length>=30} onClick={()=>patch(b.id,{rows:[...b.rows,b.rows[0].map(()=> '')]})}>Add row</button><button className="secondary" disabled={b.rows[0].length>=8} onClick={()=>patch(b.id,{rows:b.rows.map(r=>[...r,''])})}>Add column</button><button className="secondary" disabled={b.rows.length<=1} onClick={()=>patch(b.id,{rows:b.rows.slice(0,-1)})}>Remove last row</button><button className="secondary" disabled={b.rows[0].length<=1} onClick={()=>patch(b.id,{rows:b.rows.map(r=>r.slice(0,-1))})}>Remove last column</button></div><p className="fine">The first row is the table heading.</p></>}<label className="field"><span>Caption</span><input value={b.caption} maxLength={2000} onChange={e=>patch(b.id,{caption:e.target.value})}/></label><button className="textbutton" onClick={()=>change(blocks.filter(x=>x.id!==b.id))}>Remove {b.type}</button></div>)}</div>;}
