'use client';
import {useState} from 'react';
import {ProposalData,malaysiaTimestamp} from '@/lib/proposal';
export const topicFormUrl='/downloads/DDDX4356_Topic_Submission_Form_Ed10-2026.docx';
export function titleForm(value?:string):{id:string,name:string,uploadedAt:string,submittedAt?:string}|null{try{return value?JSON.parse(value):null;}catch{return null;}}
export function TitleForm({data,onUpload,onConfirm,readonly=false}:{data:ProposalData,onUpload?:(value:string)=>void,onConfirm?:(yes:boolean)=>void,readonly?:boolean}){const [uploading,setUploading]=useState(false),[error,setError]=useState('');const current=titleForm(data._titleForm),submitted=titleForm(data._titleSubmittedForm);
 const fileLink=(f:NonNullable<typeof current>,label:string)=><div className="title-file"><strong>{label}</strong><p>{f.name}</p><p className="fine">Uploaded {malaysiaTimestamp(f.uploadedAt)}{f.submittedAt&&<> · Submitted {malaysiaTimestamp(f.submittedAt)}</>}</p><div className="actions"><a className="secondary" href={'/api/media/'+f.id} target="_blank" rel="noreferrer">View form</a><a className="secondary" href={'/api/media/'+f.id+'?download=1'}>Download form</a></div></div>;
 return <section className="title-form card"><h2>Research topic submission form</h2>{readonly?<><p>The completed signed form accompanies the research title submission.</p>{submitted?fileLink(submitted,'Form submitted with research title'):<p>No form submitted with the research title yet.</p>}{current&&current.id!==submitted?.id&&fileLink(current,'Current uploaded form · not yet submitted with title')}</>:<><p>Before submitting your research title, download and complete this form. Fill in the academic session, title, student details, and supervisor details. Obtain student signatures, the main supervisor’s signature, and co-supervisor signatures where applicable.</p><a className="secondary" href={topicFormUrl} download>Download blank topic submission form · DOCX</a><p className="fine">Upload the completed signed form as PDF (recommended), DOCX, PNG or JPG, up to 10 MB. Co-supervisors are optional; include their signatures if appointed.</p>{current&&fileLink(current,'Completed form uploaded')}<label className="secondary picture-upload">{uploading?'Uploading…':current?'Replace completed form':'Upload completed signed form'}<input aria-label="Upload completed topic submission form" type="file" accept=".pdf,.docx,.png,.jpg,.jpeg" disabled={uploading} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setError('');try{const f=new FormData();f.append('purpose','titleForm');f.append('document',file);const res=await fetch('/api/media',{method:'POST',body:f});const value=await res.json() as {id:string,name:string,uploadedAt:string,error?:string};if(!res.ok)throw new Error(value.error);onUpload?.(JSON.stringify({id:value.id,name:value.name,uploadedAt:value.uploadedAt}));}catch(err){setError((err as Error).message);}finally{setUploading(false);e.target.value='';}}}/></label>{error&&<p className="error" role="alert">{error}</p>}<label className="signature-check"><input type="checkbox" disabled={!current||uploading} checked={data._titleFormConfirmed==='yes'} onChange={e=>onConfirm?.(e.target.checked)}/><span>I confirm that this form is complete and includes the student and main supervisor signatures, plus co-supervisor signatures where applicable.</span></label>{submitted&&fileLink(submitted,'Last form submitted with research title')}<p className="fine">Uploading saves a draft attachment. Click “Submit research title” to send the form and title to the course coordinator.</p></>}</section>;
}
