import {ProposalData,malaysiaTimestamp} from './proposal';
import {readExtras} from './extras';
import {exportStyle as S,exportSections,exportInventory,captionText,fieldLabel,contentsEntries,ganttPanels} from './export-model';
export async function createProposalDocx(data:ProposalData,code:string,status:string){
 const {Document,Packer,Paragraph,TextRun,ImageRun,Table,TableRow,TableCell,WidthType,HeadingLevel,Footer,PageNumber,AlignmentType,BorderStyle,VerticalAlign}=await import('docx');const {jsPDF}=await import('jspdf');const dimensions=new jsPDF(),extras=readExtras(data),inventory=exportInventory(data);const children:any[]=[];const timestamp=malaysiaTimestamp(new Date());const mmToTwip=(n:number)=>Math.round(n*56.692913);const fontData=await Promise.all(['Proposal-Regular.ttf','Proposal-Bold.ttf'].map(async name=>{const r=await fetch('/fonts/'+name);if(!r.ok)throw new Error('Unable to load export fonts. Please retry.');return new Uint8Array(await r.arrayBuffer());}));
 const text=(value:string,options:any={},size=S.body,colour=S.bodyColour,bold=false)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{after:mmToTwip(5),line:mmToTwip(4.8)},...options,children:[new TextRun({text:value,font:bold?S.boldFont:S.font,size:size*2,color:colour})]});
 const body=(value:string,justify=true,keepNext=false)=>{for(const line of (value||'Not completed').split('\n'))children.push(text(line,{alignment:justify?AlignmentType.JUSTIFIED:AlignmentType.LEFT,keepNext}));};
 const heading=(value:string,level:1|2=2,pageBreakBefore=false)=>children.push(new Paragraph({heading:level===1?HeadingLevel.HEADING_1:HeadingLevel.HEADING_2,pageBreakBefore,keepNext:true,spacing:{before:0,after:mmToTwip(level===1?4:2.5)},children:[new TextRun({text:value,font:S.boldFont,size:S.heading*2,color:S.headingColour})]}));
 const caption=(id:string)=>{const entry=inventory.find(e=>e.id===id);if(entry)children.push(text(captionText(entry),{alignment:AlignmentType.LEFT,spacing:{before:mmToTwip(2),after:mmToTwip(5),line:220}},S.caption,S.captionColour));};
 const image=async(path:string,cover=false)=>{const r=await fetch(path);if(!r.ok)throw new Error('Unable to load a proposal picture. Please retry.');const bytes=new Uint8Array(await r.arrayBuffer());const props=dimensions.getImageProperties(bytes);const w=cover?126:Math.min(S.width,props.width/props.height*155),h=cover?46:w*props.height/props.width;return new Paragraph({alignment:AlignmentType.CENTER,keepNext:true,spacing:{after:mmToTwip(6)},children:[new ImageRun({data:bytes,type:props.fileType.toLowerCase()==='jpeg'?'jpg':'png',transformation:{width:w*3.779528,height:h*3.779528}})]});};
 const table=(rows:string[][],colWidths?:number[],active?:boolean[][],headerSize=S.table,keepTogether=false)=>{const cols=rows[0].length,cws=(colWidths||Array(cols).fill(S.width/cols)).map(mmToTwip);return new Table({width:{size:mmToTwip(S.width),type:WidthType.DXA},columnWidths:cws,borders:Object.fromEntries(['top','bottom','left','right','insideHorizontal','insideVertical'].map(k=>[k,{style:BorderStyle.SINGLE,size:4,color:S.grid}])),rows:rows.map((r,i)=>new TableRow({tableHeader:i===0,cantSplit:true,children:r.map((cell,j)=>new TableCell({width:{size:cws[j],type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,margins:{top:mmToTwip(2),bottom:mmToTwip(2),left:mmToTwip(2),right:mmToTwip(2)},shading:{fill:i===0?S.headerFill:active?.[i-1]?.[j]?S.accent:'FFFFFF'},children:cell.split('\n').map(line=>text(line,{alignment:AlignmentType.LEFT,keepNext:keepTogether,spacing:{after:0,line:mmToTwip(4.3)}},i===0?headerSize:S.table,S.bodyColour,i===0))}))}))});};
 children.push(await image('/ukm-fgg.png',true));children.push(text('',{spacing:{after:mmToTwip(17)}}));heading('UNDERGRADUATE RESEARCH PROPOSAL');body('Faculty of Dentistry • Universiti Kebangsaan Malaysia',false);body(data.session,false);heading(data.title||'Untitled proposal',1);body('Proposal number: '+code+'\nVersion: '+status,false);heading('Students');body(data.students,false);heading('Supervisors');body(data.supervisors,false);body('Contact: '+(data._student1Email||data.email)+(data._studentCount==='2'?'\nStudent 2: '+data._student2Email:''),false);body('Submission to the course coordinator only. This document is not JEP UKM ethical clearance.',false);
 heading('CONTENTS',1,true);for(const item of contentsEntries(data))children.push(text(item.label,{alignment:AlignmentType.LEFT,indent:{left:mmToTwip(item.level*5)},spacing:{after:mmToTwip(item.level===0?2:0.7),line:mmToTwip(4.2)}},item.level===0?10:9,item.level===0?S.headingColour:S.bodyColour,item.level===0));
 let first=true;for(const section of exportSections){if(section.name==='5. References'&&inventory.length){let firstList=true;for(const kind of ['table','figure'] as const){const entries=inventory.filter(e=>e.kind===kind);if(entries.length){heading(kind==='table'?'List of tables':'List of figures',1,firstList);firstList=false;for(const e of entries)body(captionText(e),false);}}heading(section.name,1,true);}else heading(section.name,1,first);first=false;for(const [key,label] of section.fields){if(section.fields.length>1)heading(fieldLabel(key,label),2,key==='flowchart'&&!!data[key]?.trim());if(key==='flowchart'&&data[key]?.trim()){const steps=data[key].split('\n').filter(x=>x.trim());for(let i=0;i<steps.length;i++){children.push(table([[`${i+1}. ${steps[i]}`]],undefined,undefined,S.table,steps.length<=8));if(i<steps.length-1)children.push(text('↓',{alignment:AlignmentType.CENTER,keepNext:steps.length<=8,spacing:{after:mmToTwip(6)}},S.body,S.headingColour));}caption('auto-flowchart');}else if(key==='gantt'&&data[key]?.trim()){const panels=ganttPanels(data[key]);if(panels){for(const panel of panels){const cw=(S.width-54)/panel.months.length;children.push(table([['Activity',...panel.months.map(m=>m.slice(2))],...panel.rows.map(r=>[r.label,...r.active.map(()=> '')])],[54,...panel.months.map(()=>cw)],panel.rows.map(r=>[false,...r.active]),7));children.push(text('',{spacing:{after:mmToTwip(4)}}));}caption('auto-gantt');}else body(data[key]);}else if(data[key]?.trim()||!extras[key]?.length)body(data[key],true,!!extras[key]?.length);for(const block of extras[key]||[]){if(block.type==='table')children.push(table(block.rows));else children.push(await image('/api/media/'+block.assetId));caption(block.id);}}}
 const doc=new Document({creator:'FGG UKM Research Proposal Portal',title:data.title||'Undergraduate Research Proposal',fonts:[{name:S.font,data:fontData[0] as any},{name:S.boldFont,data:fontData[1] as any}],styles:{default:{document:{run:{font:S.font,size:S.body*2,color:S.bodyColour},paragraph:{alignment:AlignmentType.JUSTIFIED,spacing:{line:mmToTwip(4.8),after:mmToTwip(5)}}},heading1:{run:{font:S.boldFont,size:S.heading*2,color:S.headingColour}},heading2:{run:{font:S.boldFont,size:S.heading*2,color:S.headingColour}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:mmToTwip(23),bottom:mmToTwip(23),left:mmToTwip(S.margin),right:mmToTwip(S.margin),footer:mmToTwip(6)}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.LEFT,spacing:{after:50},children:[new TextRun({text:`FGG UKM | ${code}`,font:S.font,size:16,color:S.captionColour}),new TextRun({text:'\t',font:S.font}),new TextRun({children:[PageNumber.CURRENT],font:S.font,size:16,color:S.captionColour}),new TextRun({text:' / ',font:S.font,size:16,color:S.captionColour}),new TextRun({children:[PageNumber.TOTAL_PAGES],font:S.font,size:16,color:S.captionColour})],tabStops:[{type:'right',position:mmToTwip(S.width)}]}),text('Generated: '+timestamp,{alignment:AlignmentType.LEFT,spacing:{after:0}},7,S.captionColour)]})},children}]});return Packer.toBlob(doc);
}
export async function exportDOCX(data:ProposalData,code:string,status:string){const blob=await createProposalDocx(data,code,status);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${code}-${status.replaceAll(' ','-')}.docx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
