import {groups,ProposalData} from './proposal';
import {readExtras,ExtraBlock} from './extras';
export const exportStyle={font:'DejaVu Sans',boldFont:'DejaVu Sans Bold',body:10,heading:11,table:9,caption:8,bodyColour:'1E232B',headingColour:'96144D',captionColour:'73737C',grid:'D2D2D7',headerFill:'FDF6F9',accent:'BD1760',margin:22,width:166};
const overrides:Record<string,string>={location:'3.2.1 Study location',sampling:'3.2.2 Sampling method',timeline:'3.7 Study duration and timeline',flowchart:'3.7.1 Research flow chart',gantt:'3.7.2 Gantt chart'};
export const fieldLabel=(key:string,label:string)=>overrides[key]||label.replace(' (if applicable)','');
export const exportSections=[{name:'1. Background and significance',fields:groups[1].fields},{name:'2. Objectives',fields:groups[2].fields},{name:'3. Methodology',fields:[...groups[3].fields,...groups[4].fields]},{name:'4. Budget',fields:[groups[5].fields[0]]},{name:'5. References',fields:[groups[5].fields[1]]}];
export type ExportEntry={id:string,kind:'table'|'figure',number:number,label:string,field:string};
export function exportInventory(data:ProposalData){let tables=0,figures=0;const entries:ExportEntry[]=[];const extras=readExtras(data);for(const section of exportSections)for(const [field,label] of section.fields){if((field==='flowchart'||field==='gantt')&&data[field]?.trim())entries.push({id:'auto-'+field,kind:'figure',number:++figures,label:fieldLabel(field,label).replace(/^\d+(\.\d+)*\s/,''),field});for(const block of extras[field]||[]){const kind=block.type==='table'?'table':'figure';const number=kind==='table'?++tables:++figures;entries.push({id:block.id,kind,number,label:block.caption.trim()||fieldLabel(field,label).replace(/^\d+(\.\d+)*\s/,''),field});}}return entries;}
export function captionText(entry:ExportEntry){return `${entry.kind==='table'?'Table':'Figure'} ${entry.number}. ${entry.label}`;}
export function contentsEntries(data:ProposalData){const inventory=exportInventory(data);const items:{label:string,level:number}[]=[];for(const section of exportSections){if(section.name==='5. References'&&inventory.length){if(inventory.some(e=>e.kind==='table'))items.push({label:'List of tables',level:0});if(inventory.some(e=>e.kind==='figure'))items.push({label:'List of figures',level:0});}items.push({label:section.name,level:0});if(section.fields.length>1)for(const [key,label] of section.fields)items.push({label:fieldLabel(key,label),level:/^\d+\.\d+\.\d+/.test(fieldLabel(key,label))?2:1});}return items;}
export function ganttPanels(value:string){const rows=value.split('\n').filter(x=>x.trim()).map(x=>x.split('|').map(c=>c.trim()));const idx=(s:string)=>Number(s.slice(0,4))*12+Number(s.slice(5))-1;if(!rows.length||!rows.every(r=>r.length===3&&/^\d{4}-(0[1-9]|1[0-2])$/.test(r[1])&&/^\d{4}-(0[1-9]|1[0-2])$/.test(r[2])&&idx(r[2])>=idx(r[1])))return null;const start=Math.min(...rows.map(r=>idx(r[1]))),end=Math.max(...rows.map(r=>idx(r[2])));if(end-start>47)return null;const panels=[];for(let from=start;from<=end;from+=12){const to=Math.min(end,from+11);const months=Array.from({length:to-from+1},(_,i)=>`${Math.floor((from+i)/12)}-${String((from+i)%12+1).padStart(2,'0')}`);panels.push({months,rows:rows.map(r=>({label:r[0],active:months.map((_,i)=>from+i>=idx(r[1])&&from+i<=idx(r[2]))}))});}return panels;}
export function resolveEntry(data:ProposalData,id:string){return exportInventory(data).find(e=>e.id===id);}
