import {env} from 'cloudflare:workers';
import {database,adminPassword,hash,random} from './server';
import {ProposalData,malaysiaTimestamp} from './proposal';
import {coSupervisorEmails,emailPattern} from './supervisors';
const portalUrl=String((env as unknown as {PORTAL_URL?:string}).PORTAL_URL||'');
const adminEmail='dramirulfaiz@ukm.edu.my';
async function key(){const password=adminPassword();if(!password)throw new Error('Admin configuration is unavailable.');return crypto.subtle.importKey('raw',new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('fgg-email-bridge:'+password))),{name:'AES-GCM'},false,['encrypt','decrypt']);}
const encode=(bytes:Uint8Array)=>Array.from(bytes).map(n=>n.toString(16).padStart(2,'0')).join('');
const decode=(hex:string)=>new Uint8Array(hex.match(/../g)!.map(v=>parseInt(v,16)));
async function seal(secret:string){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(secret));return encode(iv)+':'+encode(new Uint8Array(bytes));}
async function open(value:string){const [iv,bytes]=value.split(':');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(iv)},await key(),decode(bytes)));}
export async function emailSetup(){const row=await database().prepare('SELECT url FROM mail_settings WHERE id=1').first<{url:string}>();return {prepared:!!row,configured:!!row?.url,url:row?.url||'',adminEmail};}
export async function prepareEmailScript(){let row=await database().prepare('SELECT encrypted_secret FROM mail_settings WHERE id=1').first<{encrypted_secret:string}>();let secret:string;if(row)secret=await open(row.encrypted_secret);else{secret=random()+random();await database().prepare("INSERT INTO mail_settings (id,url,encrypted_secret,updated_at) VALUES (1,'',?,?)").bind(await seal(secret),new Date().toISOString()).run();}return googleScript(secret);}
export async function connectEmail(url:string){if(!/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(url))throw new Error('Paste the Google Apps Script web app URL ending in /exec.');const row=await database().prepare('SELECT id FROM mail_settings WHERE id=1').first();if(!row)throw new Error('Download the email sender script first.');await database().prepare('UPDATE mail_settings SET url=?,updated_at=? WHERE id=1').bind(url,new Date().toISOString()).run();return emailSetup();}
export async function emailRecords(id?:number){const query=id?'SELECT id,kind,recipient,subject,status,attempts,last_error,created_at,sent_at FROM mail_outbox WHERE proposal_id=? ORDER BY created_at DESC':'SELECT id,proposal_id,kind,recipient,subject,status,attempts,last_error,created_at,sent_at FROM mail_outbox ORDER BY created_at DESC LIMIT 100';const q=database().prepare(query);return (await (id?q.bind(id):q).all()).results;}
export function submissionMessages(data:ProposalData,code:string,kind:'title'|'proposal',submittedAt:string){const addresses=[data._student1Email||data.email,...(data._studentCount==='2'?[data._student2Email]:[]),data._supervisorEmail,...coSupervisorEmails(data),adminEmail];const recipients=[...new Set(addresses.filter(email=>emailPattern.test(email||'')).map(e=>e.toLowerCase()))];const label=kind==='title'?'Research title':'Research proposal';const subject=`${label} submitted · ${code}`;return recipients.map(recipient=>({recipient,subject,body:`${label} submission confirmation\n\nProject: ${code}\nResearch title: ${data.title}\nStudents:\n${data.students}\nSupervisor(s):\n${data.supervisors}\nSubmitted: ${malaysiaTimestamp(submittedAt)}\n\n${kind==='title'?'The completed signed topic submission form has been submitted with the research title.':'A copy of the proposal has been submitted to the course coordinator for review.'}\n\n${recipient===adminEmail?'Review the submission in the admin dashboard: '+portalUrl+'/admin':'Return to the proposal portal to view your project: '+portalUrl}\n\nThis confirms submission only. It is not ethical clearance. For studies requiring ethical approval, submit the relevant application to FGG UKM (etikafgg@ukm.edu.my) following the faculty and JEP UKM process.\n\nFGG UKM Research Proposal Portal`}));}
export async function queueSubmission(data:ProposalData,proposal:{id:number,code:string,version:number},kind:'title'|'proposal',submittedAt:string){const messages=submissionMessages(data,proposal.code,kind,submittedAt);for(const message of messages){const id=await hash(`${proposal.id}:${kind}:${proposal.version}:${submittedAt}:${message.recipient}`);await database().prepare("INSERT OR IGNORE INTO mail_outbox (id,proposal_id,kind,recipient,subject,body,status,created_at) VALUES (?,?,?,?,?,?,'queued',?)").bind(id,proposal.id,kind,message.recipient,message.subject,message.body,submittedAt).run();}return deliverEmails(proposal.id);}
export async function deliverEmails(proposalId?:number){const settings=await database().prepare('SELECT url,encrypted_secret FROM mail_settings WHERE id=1').first<{url:string,encrypted_secret:string}>();if(!settings?.url)return {status:'awaiting_setup',message:'Submission saved. Email notices are queued until the coordinator connects the email sender.'};const secret=await open(settings.encrypted_secret);const q=database().prepare("SELECT * FROM mail_outbox WHERE status IN ('queued','failed')"+(proposalId?' AND proposal_id=?':'')+' ORDER BY created_at LIMIT 12');const rows=(await (proposalId?q.bind(proposalId):q).all<any>()).results;let failed=0,sent=0;await Promise.all(rows.map(async row=>{try{await database().prepare('UPDATE mail_outbox SET attempts=attempts+1 WHERE id=?').bind(row.id).run();const r=await fetch(settings.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret,deliveryId:row.id,to:row.recipient,subject:row.subject,text:row.body}),signal:AbortSignal.timeout(20000)});const result=await r.json() as {ok?:boolean,error?:string};if(!r.ok||!result.ok)throw new Error(result.error||'The email sender did not confirm sending.');await database().prepare("UPDATE mail_outbox SET status='sent',last_error='',sent_at=? WHERE id=?").bind(new Date().toISOString(),row.id).run();sent++;}catch(e){failed++;await database().prepare("UPDATE mail_outbox SET status='failed',last_error=? WHERE id=?").bind((e instanceof Error?e.message:'Email sender unavailable.').slice(0,500),row.id).run();}}));
 return {status:failed?'pending_retry':'sent',sent,failed,message:failed?'Submission saved. Some email notices need a retry.':'Submission saved. Email notices sent.'};}
function googleScript(secret:string){return `// FGG UKM Research Proposal Portal email sender\n// Paste into a new Google Apps Script project. Deploy as a Web app.\n// Execute as: Me. Who has access: Anyone. Copy the /exec URL into Admin > Email setup.\n// Keep this secret private. Email requests must include the secret.\nconst PORTAL_SECRET = ${JSON.stringify(secret)};\nfunction doPost(e) {\n  const result = value => ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);\n  let lock;\n  try {\n    const body = JSON.parse(e.postData.contents);\n    if (body.secret !== PORTAL_SECRET) return result({ok:false,error:'Unauthorised email request.'});\n    if (!/^[a-f0-9]{64}$/.test(body.deliveryId || '') || !/^[^\\s@,;]+@[^\\s@,;]+\\.[^\\s@,;]+$/.test(body.to || '') || typeof body.subject !== 'string' || body.subject.length > 200 || typeof body.text !== 'string' || body.text.length > 20000) return result({ok:false,error:'Invalid email request.'});\n    lock = LockService.getScriptLock(); lock.waitLock(20000);\n    const state = PropertiesService.getScriptProperties();\n    const key = 'sent-' + body.deliveryId;\n    if (state.getProperty(key)) return result({ok:true,duplicate:true});\n    if (MailApp.getRemainingDailyQuota() < 1) return result({ok:false,error:'Google account email quota reached. Retry later.'});\n    MailApp.sendEmail({to:body.to,subject:body.subject,body:body.text,name:'FGG UKM Research Proposal Portal',replyTo:'dramirulfaiz@ukm.edu.my'});\n    state.setProperty(key,String(Date.now()));\n    const cutoff = Date.now() - 30 * 86400000;\n    Object.entries(state.getProperties()).forEach(([k,v]) => { if(k.indexOf('sent-') === 0 && Number(v) < cutoff) state.deleteProperty(k); });\n    return result({ok:true});\n  } catch (error) { return result({ok:false,error:String(error.message || error)}); } finally { if(lock && lock.hasLock()) lock.releaseLock(); }\n}\n`;} 
