import {ProposalData,malaysiaTimestamp} from './proposal';
import {readExtras} from './extras';
import {exportStyle as S,exportSections,exportInventory,captionText,fieldLabel,contentsEntries,ganttPanels} from './export-model';
export async function createProposalPDF(data:ProposalData,code:string,status:string){
 const {jsPDF}=await import('jspdf');const pdf=new jsPDF({unit:'mm',format:'a4'});const extras=readExtras(data),inventory=exportInventory(data);const timestamp=malaysiaTimestamp(new Date());let y=25;const margin=S.margin,width=S.width,bottom=274;
 for(const [file,style] of [['Proposal-Regular.ttf','normal'],['Proposal-Bold.ttf','bold']]){const res=await fetch('/fonts/'+file);if(!res.ok)throw new Error('Unable to load export fonts. Please retry.');const bytes=new Uint8Array(await res.arrayBuffer());let binary='';for(let n=0;n<bytes.length;n+=8192)binary+=String.fromCharCode(...bytes.subarray(n,n+8192));pdf.addFileToVFS(file,btoa(binary));pdf.addFont(file,'Proposal',style);}
 const page=()=>{pdf.addPage();y=23;};const font=(size:number,bold=false,colour=S.bodyColour)=>{pdf.setFont('Proposal',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor('#'+colour);};
 const heading=(value:string,major=false)=>{font(S.heading,true,S.headingColour);const lines=pdf.splitTextToSize(value,width);if(y+lines.length*5.4+14>bottom)page();pdf.text(lines,margin,y);y+=lines.length*5.4+(major?4:2.5);};
 const paragraph=(value:string,justify=true,size=S.body,colour=S.bodyColour,indent=0)=>{font(size,false,colour);const lineHeight=size===S.body?4.8:4.1;for(const p of (value||'Not completed').split('\n')){const lines=pdf.splitTextToSize(p||' ',width-indent) as string[];for(let i=0;i<lines.length;i++){if(y>bottom)page();const line=lines[i],words=line.trim().split(/\s+/);if(justify&&i<lines.length-1&&words.length>1){const spaces=(width-indent-pdf.getTextWidth(words.join('')))/(words.length-1);let x=margin+indent;for(const word of words){pdf.text(word,x,y);x+=pdf.getTextWidth(word)+spaces;}}else pdf.text(line,margin+indent,y);y+=lineHeight;}y+=1;}y+=4;};
 const caption=(id:string)=>{const entry=inventory.find(e=>e.id===id);if(entry)paragraph(captionText(entry),false,S.caption,S.captionColour);};
 const table=(rows:string[][],colWidths?:number[],active?:boolean[][],headerSize=S.table)=>{const cols=rows[0].length,cws=colWidths||Array(cols).fill(width/cols);font(S.table);const wrapped=rows.map((r,ri)=>r.map((cell,ci)=>{font(ri===0?headerSize:S.table,ri===0);return pdf.splitTextToSize(cell||' ',cws[ci]-4) as string[];}));const draw=(ri:number,offset:number,count:number)=>{const h=count*4.3+4;let x=margin;for(let ci=0;ci<cols;ci++){pdf.setFillColor('#'+(ri===0?S.headerFill:active?.[ri-1]?.[ci]?S.accent:'FFFFFF'));pdf.setDrawColor('#'+S.grid);pdf.rect(x,y,cws[ci],h,'FD');font(ri===0?headerSize:S.table,ri===0);pdf.text(wrapped[ri][ci].slice(offset,offset+count),x+2,y+5);x+=cws[ci];}y+=h;};for(let ri=0;ri<rows.length;ri++){let offset=0;const max=Math.max(...wrapped[ri].map(c=>c.length));while(offset<max){if(y>bottom-10){page();if(ri>0)draw(0,0,Math.max(...wrapped[0].map(c=>c.length)));}const count=Math.min(max-offset,Math.max(1,Math.floor((bottom-y-4)/4.3)));draw(ri,offset,count);offset+=count;}}y+=6;};
 const picture=async(path:string,cover=false)=>{const r=await fetch(path);if(!r.ok)throw new Error('Unable to load a proposal picture. Please retry.');const bytes=new Uint8Array(await r.arrayBuffer());const props=pdf.getImageProperties(bytes);const w=cover?126:Math.min(width,props.width/props.height*155),h=cover?46:w*props.height/props.width;if(y+h+12>bottom)page();pdf.addImage(bytes,props.fileType,margin+(width-w)/2,y,w,h);y+=h+6;};
 await picture('/ukm-fgg.png',true);y=95;heading('UNDERGRADUATE RESEARCH PROPOSAL');paragraph('Faculty of Dentistry • Universiti Kebangsaan Malaysia',false);paragraph(data.session,false);heading(data.title||'Untitled proposal');paragraph('Proposal number: '+code+'\nVersion: '+status,false);heading('Students');paragraph(data.students,false);heading('Supervisors');paragraph(data.supervisors,false);paragraph('Contact: '+(data._student1Email||data.email)+(data._studentCount==='2'?'\nStudent 2: '+data._student2Email:''),false);y=Math.max(y,230);paragraph('Submission to the course coordinator only. This document is not JEP UKM ethical clearance.',false);
 page();heading('CONTENTS',true);for(const item of contentsEntries(data)){font(item.level===0?10:9,item.level===0,item.level===0?S.headingColour:S.bodyColour);const lines=pdf.splitTextToSize(item.label,width-item.level*5);if(y+lines.length*4.2>bottom)page();pdf.text(lines,margin+item.level*5,y);y+=lines.length*4.2+(item.level===0?2:0.7);}page();
 for(const section of exportSections){if(section.name==='5. References'&&inventory.length){page();for(const kind of ['table','figure'] as const){const entries=inventory.filter(e=>e.kind===kind);if(entries.length){heading(kind==='table'?'List of tables':'List of figures',true);for(const e of entries)paragraph(captionText(e),false);}}page();}heading(section.name,true);for(const [key,label] of section.fields){if(key==='flowchart'&&data[key]?.trim())page();if(section.fields.length>1)heading(fieldLabel(key,label));if(key==='flowchart'&&data[key]?.trim()){const steps=data[key].split('\n').filter(x=>x.trim());for(let i=0;i<steps.length;i++){table([[`${i+1}. ${steps[i]}`]]);if(i<steps.length-1)paragraph('↓',false,S.body,S.headingColour,79);}caption('auto-flowchart');}else if(key==='gantt'&&data[key]?.trim()){const panels=ganttPanels(data[key]);if(panels){for(const panel of panels){const cw=(width-54)/panel.months.length;table([['Activity',...panel.months.map(m=>m.slice(2))],...panel.rows.map(r=>[r.label,...r.active.map(()=> '')])],[54,...panel.months.map(()=>cw)],panel.rows.map(r=>[false,...r.active]),7);}caption('auto-gantt');}else paragraph(data[key]);}else if(data[key]?.trim()||!extras[key]?.length)paragraph(data[key]);for(const block of extras[key]||[]){if(block.type==='table')table(block.rows);else await picture('/api/media/'+block.assetId);caption(block.id);}}}
 const pages=pdf.getNumberOfPages();for(let n=1;n<=pages;n++){pdf.setPage(n);font(8,false,S.captionColour);pdf.text('FGG UKM | '+code,margin,288);pdf.text(`${n} / ${pages}`,188,288,{align:'right'});font(7,false,S.captionColour);pdf.text('Generated: '+timestamp,margin,293);}return pdf;
}
export async function exportPDF(data:ProposalData,code:string,status:string){const pdf=await createProposalPDF(data,code,status);pdf.save(`${code}-${status.replaceAll(' ','-')}.pdf`);return pdf.getNumberOfPages();}
