export const groups=[
 {name:'Project details',short:'Details',fields:[['title','Research title'],['students','Student names and matric numbers'],['email','Contact email'],['supervisors','Supervisors'],['session','Academic session']]},
 {name:'1. Background & significance',short:'Background',fields:[['introduction','1.1 Introduction'],['problem','1.2 Problem statement'],['justification','1.3 Justifications of the study'],['literature','1.4 Literature review'],['authenticity','1.5 Authenticity / sustainability (if applicable)']]},
 {name:'2. Objectives',short:'Objectives',fields:[['general','2.1 General objective'],['specific','2.2 Specific objectives'],['questions','2.3 Research questions'],['hypotheses','2.4 Hypotheses'],['development','2.5 Hypotheses development (if applicable)']]},
 {name:'3. Methodology',short:'Methods',fields:[['design','3.1 Study type and design'],['population','3.2 Study population'],['location','Study location'],['sampling','Type of sampling'],['inclusion','3.3 Inclusion criteria'],['exclusion','3.4 Exclusion criteria'],['withdrawal','3.5 Withdrawal criteria'],['sample','3.6 Sample size'],['timeline','3.7 Study duration and timeline (maximum 36 months, except clinical trials)'],['flowchart','Research flow chart (one step per line)'],['gantt','Gantt chart (Activity | YYYY-MM | YYYY-MM, one activity per line)'],['procedures','3.8 Study procedures'],['analysis','3.9 Statistical analysis plan']]},
 {name:'3. Ethics & governance',short:'Ethics',fields:[['risk','3.10 Risk and benefit to study participants'],['assessment','3.11 Risk–benefit assessment'],['ethics','3.12 Ethics of study'],['consent','3.13 Informed consent'],['privacy','3.14 Privacy and confidentiality'],['conflict','3.15 Conflict of interest'],['publication','3.16 Publication policy'],['termination','3.17 Termination of study']]},
 {name:'4–5. Budget & references',short:'Finish',fields:[['budget','4. Budget'],['references','5. References']]}
];
export const fields=groups.flatMap(g=>g.fields);
export type ProposalData=Record<string,string>;
export const blank=()=>Object.fromEntries([...fields.map(([k])=>[k,k==='session'?'2026/2027':'']),['ethicsStatus','Not assessed'],['_extras','{}']]);
export function fieldComplete(d:ProposalData,k:string){if(d._studentCount&&(k==='students'||k==='email')){const count=d._studentCount==='2'?2:1;for(let i=1;i<=count;i++){if(k==='students'&&(!d[`_student${i}Name`]?.trim()||!d[`_student${i}Matric`]?.trim()))return false;if(k==='email'&&!/^\S+@\S+\.\S+$/.test(d[`_student${i}Email`]||''))return false;}return true;}if(d[k]?.trim())return true;try{const blocks=JSON.parse(d._extras||'{}')[k];return Array.isArray(blocks)&&blocks.some(b=>b.type==='picture'&&b.assetId||b.type==='table'&&b.rows?.some((r:string[])=>r.some(c=>c.trim())));}catch{return false;}}
export const completion=(d:ProposalData)=>Math.round(fields.filter(([k])=>fieldComplete(d,k)).length/fields.length*100);
export const missing=(d:ProposalData)=>fields.filter(([k])=>!fieldComplete(d,k)).map(([,label])=>label);
export const deadlines=[['Research title submission','30 November 2026','2026-11-30'],['Research proposal submission','31 January 2027','2027-01-31'],['JEP UKM ethics notification and approval letter, where applicable','31 December 2027','2027-12-31'],['Abstract submission','29 February 2028','2028-02-29'],['Research report submission','31 May 2028','2028-05-31']];
export const portalNote='This portal is solely for research proposal submission to the course coordinator. You can use this proposal template to submit to FGG UKM for ethical clearance, and later for submission to JEP UKM.';
export function malaysiaTimestamp(value:string|Date){return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'medium',timeStyle:'medium',hour12:false}).format(new Date(value))+' MYT (UTC+08:00)';}
