import {env} from 'cloudflare:workers';
import {database,session,random,rate} from '@/lib/server';
export const dynamic='force-dynamic';
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return Response.json({error:'Request origin rejected.'},{status:403});
 const s=await session(req);if(!s||s.role!=='student')return Response.json({error:'Sign in to your student workspace before uploading.'},{status:401});
 if(Number(req.headers.get('content-length')||0)>11*1024*1024)return Response.json({error:'Choose a PNG or JPG picture smaller than 5 MB.'},{status:413});if(!env.BUCKET)throw new Error('Picture storage is temporarily unavailable. Please retry.');await rate(req,'upload',80);
 const form=await req.formData();const isTitle=form.get('purpose')==='titleForm';const file=form.get(isTitle?'document':'picture');if(!file||typeof file==='string'||file.size<8||file.size>(isTitle?10:5)*1024*1024)return Response.json({error:isTitle?'Choose a completed PDF, DOCX, PNG or JPG form smaller than 10 MB.':'Choose a PNG or JPG picture smaller than 5 MB.'},{status:400});
 const bytes=new Uint8Array(await file.arrayBuffer());const mime=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':isTitle&&new TextDecoder().decode(bytes.subarray(0,5))==='%PDF-'?'application/pdf':isTitle&&bytes[0]===80&&bytes[1]===75&&bytes[2]===3&&bytes[3]===4&&new TextDecoder().decode(bytes).includes('word/document.xml')?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':null;if(!mime)return Response.json({error:isTitle?'Upload the completed form as PDF, DOCX, PNG or JPG.':'Only PNG and JPG pictures are supported.'},{status:400});
 const count=await database().prepare('SELECT COUNT(*) AS n FROM assets WHERE proposal_id=?').bind(s.proposal_id).first<{n:number}>();if((count?.n||0)>=120)return Response.json({error:'This project has reached its picture upload limit.'},{status:400});
 const id=random(),key=`proposals/${s.proposal_id}/${isTitle?'title-forms/':''}${id}`;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});try{await database().prepare('INSERT INTO assets (id,proposal_id,object_key,mime,size,created_at) VALUES (?,?,?,?,?,?)').bind(id,s.proposal_id,key,mime,bytes.length,new Date().toISOString()).run();}catch(e){await env.BUCKET.delete(key);throw e;}
 return Response.json({id,url:'/api/media/'+id,name:file.name.slice(0,200),uploadedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}});
 }catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'Unable to upload the picture. Please retry.'},{status:503});}}
